# 設定ファイル（読みにくくてごめん）

########################
#     口周りの補正     #
########################

# 左右対称化モード（0:最大値 / 1:平均値 / 2:最小値）（デフォルト:0）
SymmetricMode = 0

# JawOpen 抑制
# Pucker時のJawOpen抑制係数（0.0->無効化 / 0.5->半分 / 1.0->抑制なし）（デフォルト:0.3）
PuckerJawOpenSuppression = 0.3

# JawOpen抑制の判定条件
# （デフォルト:MouthFunnelが0.25以下かつMouthPuckerが0.6以上のときにJawOpenを徐々に抑制する）
JawOpenFunnelThreshold = 0.25
JawOpenPuckerThreshold = 0.6

# JawOpenの最大値（リミッター）（デフォルト:1.0）
JawOpenMax = 1.0

######################
#     視線の補正     #
######################

# 寄り目・反り目の補正 true/false（実験的・デフォルト:true）
PreventCrossEye=true
# 寄り目・反り目補正の強さ （補正なし:0.0 <-> 正面に補正:1.0）
CrossEyeStrength= 0.8


# 目を開けているときの視線の左右同期と倍率補正（実験的・デフォルト:true）
UseCrossEyeSync=true
CrossEyeSyncOpenThreshold = 0.2
CrossEyeSyncDiffThreshold = 0.1
# 左右の視線補正倍率（実験的・UseCrossEyeSyncがtrueのときだけ有効）
EyeLeftScale = 1.0
EyeRightScale = 1.0

# まばたきや目を細めたときに上下の視線を中央に補正（実験的・デフォルト:true）
UseLidEyeCenter = true
# EyeLidがこの値よりも小さい場合に動作を開始
LidEyeCenterThreshold = 0.95
# 視線の上下をどれだけ中央に寄せるかの係数
LidEyeCenterStrength = 1.5


# 視線のリミッター
## 内側（寄り目方向）（デフォルト:1.0）
EyeInnerLimit = 1.0
## 外側（デフォルト:1.0）
EyeOuterLimit = 1.0
## 上方向（デフォルト:1.0）
EyeUpLimit = 1.0
## 下方向（デフォルト:1.0）
EyeDownLimit = 1.0

########################
#     見開き・瞬き     #
########################

# 目を見開く（EyeWide）を有効化するかどうか true/false（デフォルト:true）
UseEyeWide = true

# 目を見開くときの左右対称化を有効化するかどうか true/false（デフォルト:true）
UseEyeWideCorrection = true

# 目を見開くときの最大値 0.0-1.0（デフォルト:1.0）
EyeWideLimit = 1.0

# 目の開き具合の左右同期補正 true/false （実験的・デフォルト:true）
UseLidSync = true

# Squint時のまぶたの閉じ具合の係数 0.0-1.0（実験的・デフォルト1.0）
# （影響なし -> 0.0 / 半分閉じる -> 0.5 / Squint通りに閉じる -> 1.0）
# （注意・EyeLidが正常に動作しないことへの暫定対応なので、今後変更される可能性があります。）
SquintStrength = 1.0

########################################
#     ウィンク・瞬きロックの設定値     #
########################################
# ウィンク・まばたきの検出とロック true/false （実験的・デフォルトtrue）
# （注意・EyeLidが正常に動作しないことへの暫定対応なので、今後変更される可能性があります。）
UseWinkLock = true

# ※BlinkThresholdFrames ＜ WinkThresholdFrames ≦ WinkReleaseFramesとすること
# まばたきの検出に必要なフレーム数 （最小1）
BlinkThresholdFrames = 1

# ウィンクの検出に必要なフレーム数 （最小2）
WinkThresholdFrames = 2

# ウィンクの解除に必要なフレーム数 （最小2）
WinkReleaseFrames = 2

# ウィンクが解除されたと判定した後、再ロックされないように無視するフレーム数（初期値1・あまり影響はないはず）
WinkJustReleasedIgnoreFrames = 1

# ウィンク判定のための閾値 0.0-1.0（ウィンクで閉じているときのSquintの値・デフォルト0.85）
WinkSquintClosed = 0.85

# ウィンク解除判定のための閾値 0.0-1.0 （開いているときのSquintの値・デフォルト0.5）
WinkSquintOpen = 0.5

# 両目閉じ判定のための閾値（デフォルト0.99）
BothClosedSquint= 0.99

# 両目開き判定のための閾値 0.0-1.0（目を開いているときのOpennessの値・デフォルト0.3）
BothOpenOpenness = 0.3

# Squintで細める場合は瞬きとして判定しないようにする閾値 0.0-1.0（デフォルト0.2）
BlinkSquint = 0.2

# 両目開き判定用安全マージン（0.05）
BlinkLidThresholdOffset = 0.05 
