# 設定ファイル（読みにくくてごめん）

########################
#     口周りの補正     #
########################
# 左右対称化モード（デフォルト0）（0:最大値で対象化, 1:平均値で対象化, 2:最小値で対象化）
SymmetryMode=0

# MouthPucker時のJawOpenの開き具合の抑制度合い 0.0-1.0（係数・デフォルト0.2）
# （JawOpenを無効化 -> 0.0 / 半分にする -> 0.5 / 抑制なし -> 1.0）
PuckerJawOpenSuppression=0.2
# JawOpenを抑制するときの判定条件
# （デフォルト：MouthPuckerが0.6以上かつMouthFunnelが0.25以下のときにJawOpenを抑制する）
JawOpenPuckerThreshold=0.6
JawOpenFunnelThreshold=0.25

# 口を大きく開けすぎないよう最大値を制限する 0.0-1.0（デフォルト0.9）
JawOpenMax=0.9

####################
#     目の補正     #
####################
# 寄り目・反り目の補正 true/false（実験的・デフォルトtrue）
PreventCrossEye=true

# 寄り目・反り目の補正する強さ 0.0-1.0
# 正面に補正 -> 0.0 / 50%補正（デフォルト）-> 0.5 / 補正なし -> 1.0
CrossEyeStrength=0.5

# 目を見開く（EyeWide）を有効化するかどうか true/false（デフォルトtrue）
UseEyeWide=true

# 目を見開くときの左右対称化を有効化するかどうか true/false（デフォルトtrue）
UseEyeWideCorrection=true

# 目を見開くときの最大値 0.0-1.0（デフォルト1.0）
EyeWideLimit=1.0

# 目の開き具合の左右同期補正 true/false （実験的・デフォルトtrue）
UseLidSync=true

# Squint時のまぶたの閉じ具合の係数 0.0-1.0（実験的・デフォルト1.0）
# （影響なし -> 0.0 / 半分閉じる -> 0.5 / Squint通りに閉じる -> 1.0）
# （注意・EyeLidが正常に動作しないことへの暫定対応なので、今後変更される可能性があります。）
SquintStrength=1.0

########################################
#     ウィンク・瞬きロックの設定値     #
########################################
# ウィンク・まばたきの検出とロック true/false （実験的・デフォルトtrue）
# （注意・EyeLidが正常に動作しないことへの暫定対応なので、今後変更される可能性があります。）
UseWinkLock=true

# ※BlinkThresholdFrames ＜ WinkThresholdFrames ≦ WinkReleaseFramesとすること
# まばたきの検出に必要なフレーム数 （最小1）
BlinkThresholdFrames=1

# ウィンクの検出に必要なフレーム数 （最小2）
WinkThresholdFrames=2

# ウィンクの解除に必要なフレーム数 （最小2）
WinkReleaseFrames=2

# ウィンクが解除されたと判定した後、再ロックされないように無視するフレーム数（初期値1・あまり影響はないはず）
WinkJustReleasedIgnoreFrames=1

# ウィンク判定のための閾値 0.0-1.0（ウィンクで閉じているときのSquintの値・デフォルト0.85）
WinkSquintClosed=0.85

# ウィンク解除判定のための閾値 0.0-1.0 （開いているときのSquintの値・デフォルト0.5）
WinkSquintOpen=0.5

# 両目閉じ判定のための閾値（デフォルト0.99）
BothClosedSquint=0.99

# 両目開き判定のための閾値 0.0-1.0（目を開いているときのOpennessの値・デフォルト0.3）
BothOpenOpenness=0.3

# Squintで細める場合は瞬きとして判定しないようにする閾値 0.0-1.0（デフォルト0.2）
BlinkSquint=0.2

# 両目開き判定用安全マージン（0.05）
BlinkLidThresholdOffset=0.05 
