# 口を大きく開けすぎないよう制限する（デフォルト0.85）
JawOpenMax=0.85

# 寄り目・反り目の補正（実験的）true/false
PreventCrossEye=true
# 寄り目・反り目の補正する強さ 0.0 -> 正面に補正 / 0.5 -> 50%補正（規定値）/  1.0 -> 補正なし
CrossEyeStrength=0.5

# ウィンク・まばたきの検出とロック true/false
UseWinkLock=true
## BlinkThresholdFrames ＜ WinkThresholdFrames ≦ WinkReleaseFrames
# まばたきの検出に必要なフレーム数 （最小1）
BlinkThresholdFrames=1
# ウィンクの検出に必要なフレーム数 （最小2）
WinkThresholdFrames=2
# ウィンクの解除に必要なフレーム数 （最小2）
WinkReleaseFrames=2
# ウィンクが解除されたと判定した後、再ロックされないように無視するフレーム数（初期値1・あまり影響はないはず）
WinkJustReleasedIgnoreFrames=1

# ウィンク判定のための閾値（ウィンクで閉じているときのSquintの値・デフォルト0.85）
WinkSquintClosed=0.85
# ウィンク解除判定のための閾値（開いているときのSquintの値・デフォルト0.5）
WinkSquintOpen=0.5

# 両目閉じ判定のための閾値（デフォルト0.99）
BothClosedSquint=0.99
# 両目開き判定のための閾値（目を開いているときのOpennessの値・デフォルト0.45）
BothOpenOpenness=0.45

# 瞬き判定のための閾値（デフォルト0.2）
BlinkSquint=0.2
# 両目開き判定用安全マージン（0.05）
BlinkLidThresholdOffset=0.05 
